# Generated by Django 3.1.3 on 2020-11-15 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneticon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='life',
            name='problem',
            field=models.CharField(default='MIN', max_length=3),
        ),
        migrations.AlterField(
            model_name='population',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 15, 22, 31, 38, 871929)),
        ),
    ]
