# Generated by Django 2.2.12 on 2020-11-07 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneticon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationmethod',
            name='body',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='population',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 7, 15, 59, 52, 720379)),
        ),
    ]
