# Generated by Django 3.1.3 on 2020-12-04 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneticon', '0002_auto_20201115_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='chromosome',
            name='real_value',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='life',
            name='representation',
            field=models.CharField(default='BINARY', max_length=3),
        ),
        migrations.AlterField(
            model_name='population',
            name='create_date',
            field=models.DateField(default=datetime.time(0, 0)),
        ),
    ]
