# Generated by Django 3.1.3 on 2020-11-07 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneticon', '0002_auto_20201107_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='epoch',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='population',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 7, 22, 9, 14, 876156)),
        ),
    ]
