# Generated by Django 3.1.3 on 2020-11-08 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneticon', '0003_auto_20201107_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='epoch',
        ),
        migrations.AddField(
            model_name='chromosome',
            name='epoch',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='population',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 8, 12, 24, 20, 610690)),
        ),
    ]
