# Generated by Django 3.1.3 on 2020-11-08 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneticon', '0004_auto_20201108_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='chromosome',
            name='precision',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='population',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 8, 12, 40, 38, 85818)),
        ),
    ]
