# Generated by Django 3.1.3 on 2020-11-08 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneticon', '0005_auto_20201108_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chromosome',
            name='precision',
        ),
        migrations.AddField(
            model_name='life',
            name='precision',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='population',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 8, 18, 46, 31, 986224)),
        ),
    ]
