# Generated by Django 3.1.3 on 2020-11-08 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneticon', '0009_auto_20201108_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='population',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 8, 22, 34, 14, 837302)),
        ),
    ]
