# Generated by Django 3.1.3 on 2020-11-08 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneticon', '0010_auto_20201108_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chromosome',
            name='epoch',
        ),
        migrations.AddField(
            model_name='subject',
            name='generation',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='population',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 8, 22, 50, 16, 352484)),
        ),
    ]
